% import model
%rebase('base.tpl', title='Minolovec')



% if stanje == "ZMAGA":



<table>
    <tr>
        <th>
        </th>
        <th>
            <h2>0</h2>
        </th>
        <th>
            <h2>1</h2>
        </th>
        <th>
            <h2>2</h2>
        </th>
        <th>
            <h2>3</h2>
        </th>
        <th>
            <h2>4</h2>
        </th>
        <th>
            <h2>5</h2>
        </th>
        <th>
            <h2>6</h2>
        </th>
        <th>
            <h2>7</h2>
        </th>
        <th>
            <h2>8</h2>
        </th>
        <th>
            <h2>9</h2>
        </th>
    </tr>
    <tr>
        <th>
            <h2>0</h2>
        </th>
        <td>
            <h2>{{igra.resitev[0][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>1</h2>
        </th>
        <td>
            <h2>{{igra.resitev[1][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][9]}}</h2>
        </td>
        
    </tr>
    <tr>
        <th>
            <h2>2</h2>
        </th>
        <td>
            <h2>{{igra.resitev[2][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>3</h2>
        </th>
        <td>
            <h2>{{igra.resitev[3][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>4</h2>
        </th>
        <td>
            <h2>{{igra.resitev[4][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>5</h2>
        </th>
        <td>
            <h2>{{igra.resitev[5][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>6</h2>
        </th>
        <td>
            <h2>{{igra.resitev[6][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>7</h2>
        </th>
        <td>
            <h2>{{igra.resitev[7][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>8</h2>
        </th>
        <td>
            <h2>{{igra.resitev[8][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>9</h2>
        </th>
        <td>
            <h2>{{igra.resitev[9][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][9]}}</h2>
        </td>
    </tr>
    </table>

<h1>ZMAGA 😀</h1>

<form action="/izbira_tezavnosti/" method="post">
    <button type="submit">Nova igra</button>
</form>
<br>
<form action="/izbira_tezavnosti/" method="post">
    <button type="submit">Nova igra</button>
  </form>

% elif stanje == "PORAZ":



<table>
    <tr>
        <th>
        </th>
        <th>
            <h2>0</h2>
        </th>
        <th>
            <h2>1</h2>
        </th>
        <th>
            <h2>2</h2>
        </th>
        <th>
            <h2>3</h2>
        </th>
        <th>
            <h2>4</h2>
        </th>
        <th>
            <h2>5</h2>
        </th>
        <th>
            <h2>6</h2>
        </th>
        <th>
            <h2>7</h2>
        </th>
        <th>
            <h2>8</h2>
        </th>
        <th>
            <h2>9</h2>
        </th>
    </tr>
    <tr>
        <th>
            <h2>0</h2>
        </th>
        <td>
            <h2>{{igra.resitev[0][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[0][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>1</h2>
        </th>
        <td>
            <h2>{{igra.resitev[1][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[1][9]}}</h2>
        </td>
        
    </tr>
    <tr>
        <th>
            <h2>2</h2>
        </th>
        <td>
            <h2>{{igra.resitev[2][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[2][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>3</h2>
        </th>
        <td>
            <h2>{{igra.resitev[3][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[3][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>4</h2>
        </th>
        <td>
            <h2>{{igra.resitev[4][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[4][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>5</h2>
        </th>
        <td>
            <h2>{{igra.resitev[5][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[5][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>6</h2>
        </th>
        <td>
            <h2>{{igra.resitev[6][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[6][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>7</h2>
        </th>
        <td>
            <h2>{{igra.resitev[7][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[7][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>8</h2>
        </th>
        <td>
            <h2>{{igra.resitev[8][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[8][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>9</h2>
        </th>
        <td>
            <h2>{{igra.resitev[9][0]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][1]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][2]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][3]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][4]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][5]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][6]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][7]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][8]}}</h2>
        </td>
        <td>
            <h2>{{igra.resitev[9][9]}}</h2>
        </td>
    </tr>
    </table>

<h1>PORAZ 🙁</h1>

<form action="/izbira_tezavnosti/" method="post">
    <button type="submit">Nova igra</button>
</form>
<br>
<form action="/izbira_tezavnosti/" method="post">
    <button type="submit">Nova igra</button>
  </form>

% else:

<table>
    <tr>
        <th>
        </th>
        <th>
            <h2>0</h2>
        </th>
        <th>
            <h2>1</h2>
        </th>
        <th>
            <h2>2</h2>
        </th>
        <th>
            <h2>3</h2>
        </th>
        <th>
            <h2>4</h2>
        </th>
        <th>
            <h2>5</h2>
        </th>
        <th>
            <h2>6</h2>
        </th>
        <th>
            <h2>7</h2>
        </th>
        <th>
            <h2>8</h2>
        </th>
        <th>
            <h2>9</h2>
        </th>
    </tr>
    <tr>
        <th>
            <h2>0</h2>
        </th>
        <td>
            <h2>{{polje[0][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[0][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>1</h2>
        </th>
        <td>
            <h2>{{polje[1][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[1][9]}}</h2>
        </td>
        
    </tr>
    <tr>
        <th>
            <h2>2</h2>
        </th>
        <td>
            <h2>{{polje[2][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[2][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>3</h2>
        </th>
        <td>
            <h2>{{polje[3][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[3][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>4</h2>
        </th>
        <td>
            <h2>{{polje[4][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[4][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>5</h2>
        </th>
        <td>
            <h2>{{polje[5][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[5][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>6</h2>
        </th>
        <td>
            <h2>{{polje[6][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[6][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>7</h2>
        </th>
        <td>
            <h2>{{polje[7][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[7][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>8</h2>
        </th>
        <td>
            <h2>{{polje[8][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[8][9]}}</h2>
        </td>
    </tr>
    <tr>
        <th>
            <h2>9</h2>
        </th>
        <td>
            <h2>{{polje[9][0]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][1]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][2]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][3]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][4]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][5]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][6]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][7]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][8]}}</h2>
        </td>
        <td>
            <h2>{{polje[9][9]}}</h2>
        </td>
    </tr>
    </table>
<br>

<form action="/igra/" method="post">
    Poteza: <input type="text" name="poteza" autofocus>
    <button type="submit">Pošlji potezo</button>
</form>

%end